# Use an official Node.js image as the base image
FROM node:22.12.0

# Set the working directory in the container
WORKDIR /app

# Copy the package.json 
COPY package.json ./

# Install the frontend dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Expose the frontend port (3000)
EXPOSE 3000

# Start the backend application
CMD ["npm", "start"]
