#version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "8080:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: restaurent_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8082"
    environment:
      DB_PORT: 3306
      DB_HOST: mysql     
      DB_USER: root
      DB_PASS: ""
      DB_NAME: restaurent_db
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3001"

volumes:
  mysql_data:
