version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal  
      - DB_USER=root
      - DB_PASS=  
      - DB_NAME=restaurent-db  
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
