# Use an official Node.js image as the base image
FROM node:22.12.0

# Set the working directory in the container
WORKDIR /app

# Copy the package.json 
COPY package.json ./

# Install the backend dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose the backend port (8081)
EXPOSE 8081

# Start the backend application
CMD ["npm", "start"]
